# azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: CmdLine@2
    inputs:
      script: 'docker run -d --restart unless-stopped --name newrelic-statsd -h $(hostname) -e NR_ACCOUNT_ID=$(AccountId) -e NR_API_KEY=$(NrAPIKey) -p 8125:8125/udp -e NR_EU_REGION=true newrelic/nri-statsd:latest'

  - task: k6-load-test@0
    inputs:
      filename: 'test/k6.js'
      args: '--out statsd'

